#!/usr/bin/bash

source $1

function kill_ssh {
	if [ ! -z "$SSH_PID" ]
	then
		echo kill $SSH_PID
		kill $SSH_PID
	fi
}

trap 'kill_ssh; exit 1' INT PIPE TERM

LAST_USER_HOST=
LAST_SERVER_PORT=
LAST_PORT=
SSH_PID=
while true
do

	#echo Fetching HQ server/port from $HQ_URL
	set -- $(curl -s $HQ_URL)
	if [[ "$3" =~ ^[0-9]+$ && "$2" =~ ^[0-9]+$ && "$1" =~ ^[0-9a-zA-Z-]+@[0-9a-zA-Z.-]+$ ]]
	then
		USER_HOST=$1
		SERVER_PORT=$2
		PORT=$3
		if [[ ! ( "$USER_HOST" = "$LAST_USER_HOST" && "$SERVER_PORT" = "$LAST_SERVER_PORT" && "$PORT" = "$LAST_PORT" ) ]]
		then
			echo "HQ host/port changed, re-establishing tunnel"
			kill_ssh
			echo ssh -NT -o "Port $SERVER_PORT" -R $PORT:localhost:22 $USER_HOST
			ssh -NT -o "Port $SERVER_PORT" -R $PORT:localhost:22 $USER_HOST &
			SSH_PID=$!
			LAST_USER_HOST=$USER_HOST
			LAST_SERVER_PORT=$SERVER_PORT
			LAST_PORT=$PORT
			PRINTED_INVALID=0
		fi
	else
		if [[ $PRINTED_INVALID == 0 ]]
		then
			echo Invalid HQ server/port: $1 $2
			PRINTED_INVALID=1
			LAST_USER_HOST=
			LAST_SERVER_PORT=
			LAST_PORT=
		fi
	fi
	sleep 300
done
